apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-env
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.environment | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
