{{- if and (not .Values.rollout.enabled) (not .Values.statefulset.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-python"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/app-python/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "secret/data/app-python/config" -}}`}}
          APP_USERNAME={{ `{{ .Data.data.username }}` }}
          APP_PASSWORD={{ `{{ .Data.data.password }}` }}
          {{`{{- end -}}`}}
    spec:
      serviceAccountName: {{ include "common.fullname" . }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "common.fullname" . }}-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}-data
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        envFrom:
          - secretRef:
              name: {{ include "common.fullname" . }}-secret
          - configMapRef:
              name: {{ include "common.fullname" . }}-env
        env:
          {{- include "common.envVars" . | nindent 10 }}
        volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: data-volume
            mountPath: /data
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
{{- end }}
