version: "3.8"

services:

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    networks:
      - logging
    mem_limit: 512m
    cpus: 0.50
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - logging
    mem_limit: 128m
    cpus: 0.20

  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - logging
    mem_limit: 512m
    cpus: 0.50
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-python:
    build:
      context: ../app_python
      dockerfile: Dockerfile
    image: devops-info-service:local
    container_name: app-python
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
    labels:
      logging: "promtail"
      app: "devops-python"
    networks:
      - logging
    depends_on:
      - promtail
    mem_limit: 128m
    cpus: 0.25

volumes:
  loki-data:
  grafana-data:

networks:
  logging: