apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-python-envs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesFile: values-dev.yaml
            autoSync: true
          - env: prod
            namespace: prod
            valuesFile: values-prod.yaml
            autoSync: false
  template:
    metadata:
      name: 'app-python-{{ .env }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ssspamqe/DevOps-Core-Course.git
        targetRevision: lab12
        path: app_python/k8s/app-python
        helm:
          valueFiles:
            - '{{ .valuesFile }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if .autoSync }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    {{- end }}