apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssspamqe/DevOps-Core-Course.git
    targetRevision: lab12
    path: app_python/k8s/app-python
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true